### ISSUE TITLE
Random Prayer Penitence creates impossible puzzle in Library of the Negated Words

### ISSUE THREAD

**Issue by SteveBass7** [BrandenEK/Blasphemous-Random-Prayer-Use#1]
In **Library of the Negated Words**, in the zone near the prayer _Romance to the Crimson Mist_, you should take all your items (rosary beads, hearts, etc) and wait 9 seconds, after that the door should open.

When you are in Penitence of the Misheard Words, the door won't open, as the game thinks you have a prayer equipped.

Steps to reproduce:
1. Create a new game
2. Choose the Penitence of the Misheard Words
3. In console write `load D05Z01S09`
4. You shouldn't have anything equipped at this moment, wait more than 9 seconds, the door won't open

Here you have a [Twitch clip](https://clips.twitch.tv/HomelyCoweringLouseShadyLulu-t88nuiZD1A2AgUcv) where you can see an in game example

Workaround:
- In console write `penitence deactivate`
- When enter in the next zone, write `penitence activate PE_RANDOM_PRAYER`

**Comment by BrandenEK** [comment]
Wow, can't believe I missed this.  Thanks for informing me of this bug.  It has been fixed and a new version has been uploaded.
